modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory

modId="pixelmonrankings" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Pixelmon Rankings" #mandatory

description="Rank certains statistics from Pixelmon"

[[dependencies.pixelmonrankings]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.pixelmonrankings]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1.7,9.1.10]"
    ordering="AFTER"
    side="BOTH"
